# .kodiak.toml
version = 1

[merge]
automerge_label = "ship it"
require_automerge_label = false
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true
notify_on_conflict = false
blocking_labels = ["no automerge"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_coauthors = false
include_pr_number = true
body_type = "markdown"
strip_html_comments = true

[update]
autoupdate_label = "keep up-to-date"
